version: '3.8'

networks:
  cloud-socket-proxy:
    external: true
    
services:
  system-prune:
    image: docker
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
    command: docker system prune --all --force --volumes
    network:
      - cloud-socket-proxy
    deploy:
      mode: global
      restart_policy:
        condition: none
